local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV["S3_KEY"] %>
  secret_access_key: <%= ENV["S3_SECRET"] %>
  region: <%= ENV["S3_REGION"] %>
  bucket: <%= ENV["S3_BUCKET"] %>

dev_amazon:
  service: S3
  access_key_id: <%= ENV["RIB_S3_KEY"] %>
  secret_access_key: <%= ENV["RIB_S3_SECRET"] %>
  region: <%= ENV["RIB_S3_REGION"] %>
  bucket: <%= ENV["RIB_S3_BUCKET"] %>
